apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-cloud
spec:
  selector:
    app: {{ .Release.Name }}-app-cloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.application.ports.targetPort }}
  type: {{ .Values.application.service.type }}